### ISSUE TITLE
Training and validation cost function is very high

### ISSUE THREAD

**Issue by abdoelsayed2016** [xd92/CEIR#2]
Hello,
I want to ask about recognition training 
I am training your model with your data but the training cost function is very high
here is an example 
at epoch 0/24 
Test H: -18999992.000000, Cost: 19000042.000000, H Cost: 19000026.000000, accuray: 0.000000

is that normal at the first epoch and wait until the model finishes?

**Comment by eadst** [comment]
Hi,

The cost is high seeming normal at first. My code is probably out of fashion now. I recommend you to try their project to finetune your receipt data. 
[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)
